### ISSUE TITLE
Cron scheduling not working

### ISSUE THREAD

**Issue by dimisc** [JackDallas/TorrentCleaner#1]
The cron scheduling listed in the readme file is not working.

I noticed the directory structure is different from the actual file and also the .go file is not executed.

Please update istructions on how to automate the process of running the .go script in cron.

**Comment by JackDallas** [comment]
Hi there, afraid I haven't needed this software for a while so it's been left here, i think sonarr have updated their api since then so I doubt it works anyway, I'll likely archive this at some point but you are ofc welcome to fork it

**Comment by JackDallas** [comment]
@dimisc I changed my mind, this now runs perpetually, use something like screen (Check the updated readme) release assets are here for download https://github.com/JackDallas/SonarrTorrentCleaner/releases/tag/v2.0.0
