### ISSUE TITLE
Error removing item from Sonarr: {   "message": "MethodNotAllowed" }

### ISSUE THREAD

**Issue by OliverGrace** [JackDallas/TorrentCleaner#2]
The log shows an error. Is it because of the API logic?
```
Error removing item from Sonarr: {   "message": "MethodNotAllowed" }
```
```
Version
3.0.6.1342
Package Version
3.0.6.1342-ls128 by linuxserver.io
Mono Version
5.20.1.34
AppData directory
/config
Startup directory
/app/sonarr/bin
Mode
Console
```

**Comment by nsaintot** [comment]
[HTTP Queue](https://github.com/Sonarr/Sonarr/wiki/Queue)
per their wiki the payload is not passed in the body but as parameters:
```
Parameters
Required: id (int) Unique ID of the command

Optional: blacklist (bool) Set to 'true' to blacklist after delete
```

**Comment by OliverGrace** [comment]
After checking, found that cleaner not in the same network as sonarr docker.

**Comment by JackDallas** [comment]
> [HTTP Queue](https://github.com/Sonarr/Sonarr/wiki/Queue) per their wiki the payload is not passed in the body but as parameters:
> 
> ```
> Parameters
> Required: id (int) Unique ID of the command
> 
> Optional: blacklist (bool) Set to 'true' to blacklist after delete
> ```

As in query params ? Huh this has worked for me, I'll try that way at some point in case I'm hitting an undocumented endpoint
